env:
  es6: true
  node: true
extends: 'eslint:recommended'
parser: 'babel-eslint'
plugins:
  - react
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  semi:
    - error
    - always
